# Generated by Django 4.1.3 on 2023-01-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
