# Generated by Django 4.1.3 on 2023-01-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_application_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='price',
        ),
    ]
