# Generated by Django 4.1.3 on 2023-01-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_application_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parts_all_price',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.parts'),
        ),
    ]
