# Generated by Django 4.1.3 on 2023-01-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_application_parts_all_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='parts_all_price',
        ),
    ]
