# Generated by Django 4.1.3 on 2023-01-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_application_parts_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='count_parts',
            field=models.IntegerField(default=1, verbose_name='Количество деталей'),
        ),
    ]
