# Generated by Django 4.1.3 on 2023-01-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_parts_count_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='parts',
            name='count_parts',
            field=models.IntegerField(default=0, verbose_name='Количество деталей'),
        ),
        migrations.AddField(
            model_name='application',
            name='services_workshop',
            field=models.ManyToManyField(to='main.services', verbose_name='Услуги сервиса'),
        ),
    ]
