# Generated by Django 4.1.3 on 2023-01-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_services_alter_parts_count_parts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='services_workshop',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
