# Generated by Django 4.1.3 on 2023-01-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_application_services_workshop_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='all_price',
            field=models.IntegerField(default=0, verbose_name='Общая сумма деталей'),
        ),
        migrations.AddField(
            model_name='parts',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name='Бренд детали'),
        ),
    ]
